In [4]:
import tensorflow as tf
import numpy as np

In [2]:
WGS_84_EARTH_MU = 3.986004418e14


In [7]:
orbit0 = np.array([7999e3, 1e-4, 0, 0.2, 0.1, 0.7], ndmin=2)
orbit0.shape

(1, 6)

In [18]:
time = np.arange(0, 7200, 600, dtype='float').reshape(-1 , 1)
time.shape

(12, 1)

In [40]:
def numpy_kepler_propagate(orbit, time):
    semi_major_axis = orbit[0, 0]
    mean_motion = np.sqrt(WGS_84_EARTH_MU/semi_major_axis)/semi_major_axis
    rate = np.array([0, 0, 0, 0, 0, mean_motion], ndmin=2)
    orbit_update = rate*time
    return orbit + orbit_update

numpy_kepler_propagate(orbit0, time)

array([[7.99900000e+06, 1.00000000e-04, 0.00000000e+00, 2.00000000e-01,
        1.00000000e-01, 7.00000000e-01],
       [7.99900000e+06, 1.00000000e-04, 0.00000000e+00, 2.00000000e-01,
        1.00000000e-01, 1.22950077e+00],
       [7.99900000e+06, 1.00000000e-04, 0.00000000e+00, 2.00000000e-01,
        1.00000000e-01, 1.75900153e+00],
       [7.99900000e+06, 1.00000000e-04, 0.00000000e+00, 2.00000000e-01,
        1.00000000e-01, 2.28850230e+00],
       [7.99900000e+06, 1.00000000e-04, 0.00000000e+00, 2.00000000e-01,
        1.00000000e-01, 2.81800307e+00],
       [7.99900000e+06, 1.00000000e-04, 0.00000000e+00, 2.00000000e-01,
        1.00000000e-01, 3.34750383e+00],
       [7.99900000e+06, 1.00000000e-04, 0.00000000e+00, 2.00000000e-01,
        1.00000000e-01, 3.87700460e+00],
       [7.99900000e+06, 1.00000000e-04, 0.00000000e+00, 2.00000000e-01,
        1.00000000e-01, 4.40650536e+00],
       [7.99900000e+06, 1.00000000e-04, 0.00000000e+00, 2.00000000e-01,
        1.00000000e-01, 

In [49]:
@tf.function
def tf_kepler_propagate(orbit, time):
    semi_major_axis, *other_kepler_elements = tf.split(orbit, [1, 5], 1)
    mean_motion = tf.sqrt(WGS_84_EARTH_MU/semi_major_axis)/semi_major_axis
    rate = tf.concat([tf.zeros(shape=(1, 5), dtype='float64'), mean_motion], axis=1)
    orbit_update = rate*time
    return orbit + orbit_update

tf_kepler_propagate(orbit0, time)

<tf.Tensor: shape=(12, 6), dtype=float64, numpy=
array([[7.99900000e+06, 1.00000000e-04, 0.00000000e+00, 2.00000000e-01,
        1.00000000e-01, 7.00000000e-01],
       [7.99900000e+06, 1.00000000e-04, 0.00000000e+00, 2.00000000e-01,
        1.00000000e-01, 1.22950077e+00],
       [7.99900000e+06, 1.00000000e-04, 0.00000000e+00, 2.00000000e-01,
        1.00000000e-01, 1.75900153e+00],
       [7.99900000e+06, 1.00000000e-04, 0.00000000e+00, 2.00000000e-01,
        1.00000000e-01, 2.28850230e+00],
       [7.99900000e+06, 1.00000000e-04, 0.00000000e+00, 2.00000000e-01,
        1.00000000e-01, 2.81800307e+00],
       [7.99900000e+06, 1.00000000e-04, 0.00000000e+00, 2.00000000e-01,
        1.00000000e-01, 3.34750383e+00],
       [7.99900000e+06, 1.00000000e-04, 0.00000000e+00, 2.00000000e-01,
        1.00000000e-01, 3.87700460e+00],
       [7.99900000e+06, 1.00000000e-04, 0.00000000e+00, 2.00000000e-01,
        1.00000000e-01, 4.40650536e+00],
       [7.99900000e+06, 1.00000000e-04, 0.00000

In [50]:
import tf2001

In [51]:
tf2001.kepler_propagate(orbit0, time)

<tf.Tensor: shape=(12, 6), dtype=float64, numpy=
array([[7.99900000e+06, 1.00000000e-04, 0.00000000e+00, 2.00000000e-01,
        1.00000000e-01, 7.00000000e-01],
       [7.99900000e+06, 1.00000000e-04, 0.00000000e+00, 2.00000000e-01,
        1.00000000e-01, 1.22950077e+00],
       [7.99900000e+06, 1.00000000e-04, 0.00000000e+00, 2.00000000e-01,
        1.00000000e-01, 1.75900153e+00],
       [7.99900000e+06, 1.00000000e-04, 0.00000000e+00, 2.00000000e-01,
        1.00000000e-01, 2.28850230e+00],
       [7.99900000e+06, 1.00000000e-04, 0.00000000e+00, 2.00000000e-01,
        1.00000000e-01, 2.81800307e+00],
       [7.99900000e+06, 1.00000000e-04, 0.00000000e+00, 2.00000000e-01,
        1.00000000e-01, 3.34750383e+00],
       [7.99900000e+06, 1.00000000e-04, 0.00000000e+00, 2.00000000e-01,
        1.00000000e-01, 3.87700460e+00],
       [7.99900000e+06, 1.00000000e-04, 0.00000000e+00, 2.00000000e-01,
        1.00000000e-01, 4.40650536e+00],
       [7.99900000e+06, 1.00000000e-04, 0.00000